- name: Update all packages  
  hosts: all
  become: true
  tasks:
  - name: updating packages
    command: sudo apt-get update -y
  - name: install curl
    command: sudo apt-get install curl -y
  - name: Install NGinx
    command: sudo apt install nginx-core -y