- name: Update all packages  
  hosts: [instances]
  become: true
  gather_facts: no
  tasks:
  - name: "Wait for system to become reachable"
    wait_for_connection:
  - name: "Gather Facts"
    setup:
  - name: updating packages
    command: sudo apt-get update -y
  - name: install curl
    command: sudo apt-get install curl -y
  - name: install curl
    command: sudo apt-get install curl -y
  - name: install googler
    command: sudo apt install googler -y
  - name: 'Install NGINX'
    apt:
      name: nginx
      state: latest
  - name: 'Start NGINX Service'
    service:
      name: nginx
      state: started