- name: Joint install  
  hosts: [all_instances]
  become: true
  gather_facts: no
  tasks:
  - name: "Wait for system to become reachable"
    wait_for_connection:
  - name: "Gather Facts"
    setup:
  - name: "Install docker dependencies"
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      update_cache: true
  - name: "add gpg key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: "add repo"
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: "Install docker engine"
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: "Install with pip"
    pip:
      name:
        - docker
        - jsondiff
      executable: pip3


- name: Backend install  
  hosts: [backend]
  become: true
  gather_facts: no
  tasks:
  - name: "Wait for system to become reachable"
    wait_for_connection:
  - name: "Gather Facts"
    setup:
  - name: Create file
    command: touch test.txt
  - name: Pull Backend Docker Image
    docker_image:
      name: luffy991/backend_image:latest
      source: pull

  - name: Run the pulled backend image
    docker_container:
      name: my_backend_container
      image: luffy991/backend_image:latest
      state: started
      ports:
        - "9966:9966"

- name: Frontend install 
  hosts: [frontend]
  become: true
  gather_facts: no
  tasks:

  - name: Pull Frontend Docker Image
    docker_image:
      name: luffy991/frontend_image:latest
      source: pull

  - name: Run the pulled frontend image
    docker_container:
      name: my_frontend_container
      image: luffy991/frontend_image:latest
      state: started
      ports:
        - "8080:8080"