- name: Update all packages  
  hosts: [instances]
  become: true
  tasks:
  - name: updating packages
    command: sudo apt-get update -y
  - name: install curl
    command: sudo apt-get install curl -y
  - name: install curl
    command: sudo apt-get install curl -y
  - name: install terminator
    command: sudo apt install terminator -y
  - name: 'Install NGINX'
    apt:
      name: nginx
      state: latest
  - name: 'Start NGINX Service'
    service:
      name: nginx
      state: started