- name: Update all packages  
  hosts: localhost
  become: true
  tasks:
    - name: updating packages
      command: sudo apt-get update -y

  # install docker 
    # - name: Install docker
    #   become: true
    #   shell: curl https://get.docker.com | sh

# - name : Pull Docker image backend
#   hosts: backend
#   become: true
#   tasks :
#     - name: pulling docker image artifact from pipeline
