- name: Update all packages  
  hosts: all
  become: true
  tasks:
  - name: updating packages
    command: sudo apt-get update -y
  - name: install curl
    command: sudo apt install curl -y
    
  - name: Install Docker
    apt:
      name: docker
      state: latest
      version: latest